name: Build and push to DockerHub
on: [ push, pull_request ]
permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Inject slug/short environment variables
      uses: rlespinasse/github-slug-action@v3.x
    - name: Decide whether to push to DockerHub, and set tag
      if: |
        github.event_name == 'push' &&
        ( startsWith( github.ref, 'refs/tags/' ) ||
          contains( fromJSON('["master","develop","testnet","hardfork"]'), env.GITHUB_REF_NAME ) )
      run: |
        if [[ "${GITHUB_REF_NAME}" == "master" ]] ; then
          DOCKER_PUSH_TAG=latest
        else
          DOCKER_PUSH_TAG=${GITHUB_REF_NAME}
        fi
        echo "DOCKER_PUSH_TAG=${DOCKER_PUSH_TAG}"
        echo "DOCKER_PUSH_TAG=${DOCKER_PUSH_TAG}" >> $GITHUB_ENV
    - name: Test tag
      if: env.DOCKER_PUSH_TAG != ''
      run: echo "${DOCKER_PUSH_TAG}"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build only
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
    - name: Login to DockerHub
      if: env.DOCKER_PUSH_TAG != ''
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to DockerHub
      if: env.DOCKER_PUSH_TAG != ''
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: bitshares/bitshares-core:${{ env.DOCKER_PUSH_TAG }}
